<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; Data Wrangling – Programming for Analytics in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./data-visualization.html" rel="next">
<link href="./data-frames.html" rel="prev">
<link href="./cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ae9c50c8c79159b126e2153c26109f93.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./data-analysis.html">Data Analysis</a></li><li class="breadcrumb-item"><a href="./data-wrangling.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data Wrangling</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Programming for Analytics in R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/jhelvy/p4a/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programming</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting Started</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./operators-data-types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Operators &amp; Data Types</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./functions-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Functions &amp; Packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./creating-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Creating Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conditionals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Conditionals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing-debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Testing &amp; Debugging</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./iteration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Iteration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Strings</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./data-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-frames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data Frames</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-wrangling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./extensions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extensions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monte-carlo-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Monte Carlo Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./python-in-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Introduction to Python (in R)</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-setup" id="toc-r-setup" class="nav-link active" data-scroll-target="#r-setup"><span class="header-section-number">12.1</span> R Setup</a></li>
  <li><a href="#data-wrangling-with-dplyr" id="toc-data-wrangling-with-dplyr" class="nav-link" data-scroll-target="#data-wrangling-with-dplyr"><span class="header-section-number">12.2</span> Data wrangling with <code>dplyr</code></a>
  <ul class="collapse">
  <li><a href="#what-is-dplyr" id="toc-what-is-dplyr" class="nav-link" data-scroll-target="#what-is-dplyr"><span class="header-section-number">12.2.1</span> What is <code>dplyr</code></a></li>
  <li><a href="#select-columns-with-select" id="toc-select-columns-with-select" class="nav-link" data-scroll-target="#select-columns-with-select"><span class="header-section-number">12.2.2</span> Select columns with <code>select()</code></a></li>
  <li><a href="#select-rows-with-filter" id="toc-select-rows-with-filter" class="nav-link" data-scroll-target="#select-rows-with-filter"><span class="header-section-number">12.2.3</span> Select rows with <code>filter()</code></a></li>
  <li><a href="#sequence-operations-with-pipes" id="toc-sequence-operations-with-pipes" class="nav-link" data-scroll-target="#sequence-operations-with-pipes"><span class="header-section-number">12.2.4</span> Sequence operations with pipes (<code>%&gt;%</code>)</a></li>
  <li><a href="#sort-rows-with-arrange" id="toc-sort-rows-with-arrange" class="nav-link" data-scroll-target="#sort-rows-with-arrange"><span class="header-section-number">12.2.5</span> Sort rows with <code>arrange()</code></a></li>
  <li><a href="#create-new-variables-with-mutate" id="toc-create-new-variables-with-mutate" class="nav-link" data-scroll-target="#create-new-variables-with-mutate"><span class="header-section-number">12.2.6</span> Create new variables with <code>mutate()</code></a></li>
  </ul></li>
  <li><a href="#split-apply-combine" id="toc-split-apply-combine" class="nav-link" data-scroll-target="#split-apply-combine"><span class="header-section-number">12.3</span> Split-apply-combine</a>
  <ul class="collapse">
  <li><a href="#the-group_by-function" id="toc-the-group_by-function" class="nav-link" data-scroll-target="#the-group_by-function"><span class="header-section-number">12.3.1</span> The <code>group_by()</code> function</a></li>
  <li><a href="#the-summarize-function" id="toc-the-summarize-function" class="nav-link" data-scroll-target="#the-summarize-function"><span class="header-section-number">12.3.2</span> The <code>summarize()</code> function</a></li>
  <li><a href="#counting" id="toc-counting" class="nav-link" data-scroll-target="#counting"><span class="header-section-number">12.3.3</span> Counting</a></li>
  </ul></li>
  <li><a href="#exporting-data" id="toc-exporting-data" class="nav-link" data-scroll-target="#exporting-data"><span class="header-section-number">12.4</span> Exporting data</a></li>
  <li><a href="#tips" id="toc-tips" class="nav-link" data-scroll-target="#tips"><span class="header-section-number">12.5</span> Tips</a></li>
  <li><a href="#page-sources" id="toc-page-sources" class="nav-link" data-scroll-target="#page-sources">Page sources</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/jhelvy/p4a/edit/main/data-wrangling.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/jhelvy/p4a/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./data-analysis.html">Data Analysis</a></li><li class="breadcrumb-item"><a href="./data-wrangling.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data Wrangling</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-data-wrangling" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<h3 id="learning-objectives" class="unnumbered anchored">Learning Objectives</h3>
<ul>
<li>Describe the purpose of the <code>dplyr</code> package.</li>
<li>Select certain <em>columns</em> in a data frame with the <code>select</code> function.</li>
<li>Select certain <em>rows</em> in a data frame according to filtering conditions with the <code>filter</code> function.</li>
<li>Link the output of one <code>dplyr</code> function to the input of another function with the “pipe” operator <code>%&gt;%</code>.</li>
<li>Add new columns to a data frame that are functions of existing columns with the <code>mutate</code> function.</li>
<li>Sort data frames using the <code>arrange()</code> function.</li>
<li>Use the split-apply-combine concept for data analysis.</li>
<li>Use <code>summarize</code>, <code>group_by</code>, and <code>count</code> to split a data frame into groups of observations, apply summary statistics for each group, and then combine the results.</li>
<li>Export a data frame to a .csv file.</li>
</ul>
<h3 id="suggested-readings" class="unnumbered anchored">Suggested Readings</h3>
<ul>
<li><a href="https://r4ds.had.co.nz/transform.html">Chapter 5</a> of “R for Data Science”, by Garrett Grolemund and Hadley Wickham</li>
<li><a href="https://posit.co/resources/cheatsheets/"><code>dplyr</code> cheatsheet</a></li>
</ul>
</blockquote>
<section id="r-setup" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="r-setup"><span class="header-section-number">12.1</span> R Setup</h2>
<p>Before we get started, let’s set up our analysis environment:</p>
<ol type="1">
<li>Open up your “data-analysis-tutorial” R Project that you created in the last lesson - if you didn’t do this, <a href="data-frames.html#r-setup">go back and do it now</a>.</li>
<li>Create a new <code>.R</code> file (File &gt; New File &gt; R Script), and save it as “<code>data_wrangling.R</code>” inside your “data-analysis-tutorial” R Project folder.</li>
<li>Use the <code>download.file()</code> function to download the <code>wildlife_impacts.csv</code> dataset, and save it in the <code>data</code> folder in your R Project:</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">url =</span> <span class="st">"https://github.com/jhelvy/p4a/raw/main/data/wildlife_impacts.csv"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">destfile =</span> <span class="fu">file.path</span>(<span class="st">'data'</span>, <span class="st">'wildlife_impacts.csv'</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For this lesson, we are going to use the <a href="https://wildlife.faa.gov/">FAA Wildlife Strike Database</a>, which contains records of reported wildlife strikes with aircraft since 1990. Since aircraft-wildlife impacts are voluntarily reported, the database only contains information from airlines, airports, pilots, and other sources and does not represent all strikes. Each row in the dataset holds information for a single strike event with the following columns:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 15%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Class</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>incident_date</td>
<td>date</td>
<td>Date of incident</td>
</tr>
<tr class="even">
<td>state</td>
<td>character</td>
<td>State</td>
</tr>
<tr class="odd">
<td>airport_id</td>
<td>character</td>
<td>ICAO Airport ID</td>
</tr>
<tr class="even">
<td>airport</td>
<td>character</td>
<td>Airport Name</td>
</tr>
<tr class="odd">
<td>operator</td>
<td>character</td>
<td>Operator/Airline</td>
</tr>
<tr class="even">
<td>atype</td>
<td>character</td>
<td>Airline type</td>
</tr>
<tr class="odd">
<td>type_eng</td>
<td>character</td>
<td>Engine type</td>
</tr>
<tr class="even">
<td>species_id</td>
<td>character</td>
<td>Species ID</td>
</tr>
<tr class="odd">
<td>species</td>
<td>character</td>
<td>Species</td>
</tr>
<tr class="even">
<td>damage</td>
<td>character</td>
<td>Damage: N None M Minor, M Uncertain, S Substantial, D Destroyed</td>
</tr>
<tr class="odd">
<td>num_engs</td>
<td>character</td>
<td>Number of engines</td>
</tr>
<tr class="even">
<td>incident_month</td>
<td>double</td>
<td>Incident month</td>
</tr>
<tr class="odd">
<td>incident_year</td>
<td>double</td>
<td>Incident year</td>
</tr>
<tr class="even">
<td>time_of_day</td>
<td>character</td>
<td>Incident Time of day</td>
</tr>
<tr class="odd">
<td>time</td>
<td>double</td>
<td>Incident time</td>
</tr>
<tr class="even">
<td>height</td>
<td>double</td>
<td>Plane height at impact (feet)</td>
</tr>
<tr class="odd">
<td>speed</td>
<td>double</td>
<td>Plane speed at impact (knots)</td>
</tr>
<tr class="even">
<td>phase_of_flt</td>
<td>character</td>
<td>Phase of flight at impact</td>
</tr>
<tr class="odd">
<td>sky</td>
<td>character</td>
<td>Sky condition</td>
</tr>
<tr class="even">
<td>precip</td>
<td>character</td>
<td>Precipitation</td>
</tr>
<tr class="odd">
<td>cost_repairs_infl_adj</td>
<td>double</td>
<td>Cost of repairs adjusted for inflation</td>
</tr>
</tbody>
</table>
<p>Let’s load our libraries and read in the data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">file.path</span>(<span class="st">'data'</span>, <span class="st">'wildlife_impacts.csv'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Just like in the last lesson, a good starting point when working with a new dataset is to view some quick summaries. Here’s another summary function (<code>glimpse()</code>) that is similar to <code>str()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Rows: 56,978
#&gt; Columns: 21
#&gt; $ incident_date         &lt;dttm&gt; 2018-12-31, 2018-12-29, 2018-12-29, 2018-12-…
#&gt; $ state                 &lt;chr&gt; "FL", "IN", "N/A", "N/A", "N/A", "FL", "FL", …
#&gt; $ airport_id            &lt;chr&gt; "KMIA", "KIND", "ZZZZ", "ZZZZ", "ZZZZ", "KMIA…
#&gt; $ airport               &lt;chr&gt; "MIAMI INTL", "INDIANAPOLIS INTL ARPT", "UNKN…
#&gt; $ operator              &lt;chr&gt; "AMERICAN AIRLINES", "AMERICAN AIRLINES", "AM…
#&gt; $ atype                 &lt;chr&gt; "B-737-800", "B-737-800", "UNKNOWN", "B-737-9…
#&gt; $ type_eng              &lt;chr&gt; "D", "D", NA, "D", "D", "D", "D", "D", "D", "…
#&gt; $ species_id            &lt;chr&gt; "UNKBL", "R", "R2004", "N5205", "J2139", "UNK…
#&gt; $ species               &lt;chr&gt; "Unknown bird - large", "Owls", "Short-eared …
#&gt; $ damage                &lt;chr&gt; "M?", "N", NA, "M?", "M?", "N", "N", "N", "N"…
#&gt; $ num_engs              &lt;dbl&gt; 2, 2, NA, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,…
#&gt; $ incident_month        &lt;dbl&gt; 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 1…
#&gt; $ incident_year         &lt;dbl&gt; 2018, 2018, 2018, 2018, 2018, 2018, 2018, 201…
#&gt; $ time_of_day           &lt;chr&gt; "Day", "Night", NA, NA, NA, "Day", "Night", N…
#&gt; $ time                  &lt;dbl&gt; 1207, 2355, NA, NA, NA, 955, 948, NA, NA, 132…
#&gt; $ height                &lt;dbl&gt; 700, 0, NA, NA, NA, NA, 600, NA, NA, 0, NA, 0…
#&gt; $ speed                 &lt;dbl&gt; 200, NA, NA, NA, NA, NA, 145, NA, NA, 130, NA…
#&gt; $ phase_of_flt          &lt;chr&gt; "Climb", "Landing Roll", NA, NA, NA, "Approac…
#&gt; $ sky                   &lt;chr&gt; "Some Cloud", NA, NA, NA, NA, NA, "Some Cloud…
#&gt; $ precip                &lt;chr&gt; "None", NA, NA, NA, NA, NA, "None", NA, NA, "…
#&gt; $ cost_repairs_infl_adj &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…</code></pre>
</div>
</div>
<p>Wow, there have been 56,978 reported wildlife strikes over the 29 period from 1990 to 2019! On a daily average that comes out to:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df) <span class="sc">/</span> (<span class="dv">2019</span> <span class="sc">-</span> <span class="dv">1990</span>) <span class="sc">/</span> <span class="dv">365</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; [1] 5.3829</code></pre>
</div>
</div>
<p>…over 5 strikes per day!</p>
</section>
<section id="data-wrangling-with-dplyr" class="level2 page-columns page-full" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="data-wrangling-with-dplyr"><span class="header-section-number">12.2</span> Data wrangling with <code>dplyr</code></h2>
<div class="page-columns page-full"><p><img src="images/horst_monsters_data_wrangling.png" class="img-fluid" width="600"> </p><div class="no-row-height column-margin column-container"><span class="margin-aside">Art by <a href="https://github.com/allisonhorst/stats-illustrations">Allison Horst</a></span></div></div>
<p>“Data Wrangling” refers to the art of getting your data into R in a useful form for visualization and modeling. Wrangling is the first step in the general data science process:</p>
<center>
<img src="images/data-wrangle.png" class="img-fluid" width="600">
</center>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="margin-aside"><a href="https://r4ds.had.co.nz/introduction.html">Image source</a></span></div></div>
<section id="what-is-dplyr" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="what-is-dplyr"><span class="header-section-number">12.2.1</span> What is <code>dplyr</code></h3>
<p>As we saw in the last section, we can use brackets (<code>[]</code>) to access elements of a data frame. While this is handy, it can be cumbersome and difficult to read, especially for complicated operations.</p>
<p><strong>Enter <code>dplyr</code></strong></p>
<p>The <code>dplyr</code> package was designed to make tabular data wrangling easier to perform and read. It pairs nicely with other libraries, such as <strong><code>ggplot2</code></strong> for visualizing data (which we’ll cover next week). Together, <code>dplyr</code>, <code>ggplot2</code>, and a handful of other packages make up what is known as the <a href="https://www.tidyverse.org/">“Tidyverse”</a> - an opinionated collection of R packages designed for data science. You can load all of the tidyverse packages at once using the <code>library(tidyverse)</code> command, but for now we’re just going to install and use each package one at a time - starting with <code>dplyr</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this lesson, we are going to learn some of the most common <code>dplyr</code> functions:</p>
<ul>
<li><code>select()</code>: subset columns</li>
<li><code>filter()</code>: subset rows on conditions</li>
<li><code>mutate()</code>: create new columns by using information from other columns</li>
<li><code>arrange()</code>: sort results</li>
<li><code>group_by()</code>: group data to perform grouped operations</li>
<li><code>summarize()</code>: create summary statistics (usually on grouped data)</li>
<li><code>count()</code>: count discrete rows</li>
</ul>
</section>
<section id="select-columns-with-select" class="level3" data-number="12.2.2">
<h3 data-number="12.2.2" class="anchored" data-anchor-id="select-columns-with-select"><span class="header-section-number">12.2.2</span> Select columns with <code>select()</code></h3>
<p><img src="images/rstudio-cheatsheet-select.png" class="img-fluid" width="600"></p>
<p>To select specific columns, use <code>select()</code>. The first argument to this function is the data frame (<code>df</code>), and the subsequent arguments are the columns to keep:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select only a few columns</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df, state, damage, time_of_day)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 56,978 × 3
#&gt;   state damage time_of_day
#&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;      
#&gt; 1 FL    M?     Day        
#&gt; 2 IN    N      Night      
#&gt; 3 N/A   &lt;NA&gt;   &lt;NA&gt;       
#&gt; 4 N/A   M?     &lt;NA&gt;       
#&gt; 5 N/A   M?     &lt;NA&gt;       
#&gt; 6 FL    N      Day        
#&gt; # ℹ 56,972 more rows</code></pre>
</div>
</div>
<p>To select all columns <em>except</em> certain ones, put a <code>-</code> sign in front of the variable to exclude it:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df, <span class="sc">-</span>state, <span class="sc">-</span>damage, <span class="sc">-</span>time_of_day)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 56,978 × 18
#&gt;   incident_date       airport_id airport   operator atype type_eng species_id
#&gt;   &lt;dttm&gt;              &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;     
#&gt; 1 2018-12-31 00:00:00 KMIA       MIAMI IN… AMERICA… B-73… D        UNKBL     
#&gt; 2 2018-12-29 00:00:00 KIND       INDIANAP… AMERICA… B-73… D        R         
#&gt; 3 2018-12-29 00:00:00 ZZZZ       UNKNOWN   AMERICA… UNKN… &lt;NA&gt;     R2004     
#&gt; 4 2018-12-27 00:00:00 ZZZZ       UNKNOWN   AMERICA… B-73… D        N5205     
#&gt; 5 2018-12-27 00:00:00 ZZZZ       UNKNOWN   AMERICA… B-73… D        J2139     
#&gt; 6 2018-12-27 00:00:00 KMIA       MIAMI IN… AMERICA… A-319 D        UNKB      
#&gt; # ℹ 56,972 more rows
#&gt; # ℹ 11 more variables: species &lt;chr&gt;, num_engs &lt;dbl&gt;, incident_month &lt;dbl&gt;,
#&gt; #   incident_year &lt;dbl&gt;, time &lt;dbl&gt;, height &lt;dbl&gt;, speed &lt;dbl&gt;,
#&gt; #   phase_of_flt &lt;chr&gt;, sky &lt;chr&gt;, precip &lt;chr&gt;, cost_repairs_infl_adj &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Some additional options to select columns based on a specific criteria include:</p>
<ol type="1">
<li><code>ends_with()</code> = Select columns that end with a character string</li>
<li><code>contains()</code> = Select columns that contain a character string</li>
<li><code>matches()</code> = Select columns that match a regular expression</li>
<li><code>one_of()</code> = Select column names that are from a group of names</li>
</ol>
</section>
<section id="select-rows-with-filter" class="level3" data-number="12.2.3">
<h3 data-number="12.2.3" class="anchored" data-anchor-id="select-rows-with-filter"><span class="header-section-number">12.2.3</span> Select rows with <code>filter()</code></h3>
<p><img src="images/rstudio-cheatsheet-filter.png" class="img-fluid" width="600"></p>
<p>Filter the rows for wildlife impacts that occurred in DC:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(df, state <span class="sc">==</span> <span class="st">'DC'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1,228 × 21
#&gt;   incident_date       state airport_id airport        operator atype type_eng
#&gt;   &lt;dttm&gt;              &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;          &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;   
#&gt; 1 2018-10-23 00:00:00 DC    KDCA       RONALD REAGAN… AMERICA… B-73… D       
#&gt; 2 2018-10-17 00:00:00 DC    KDCA       RONALD REAGAN… AMERICA… B-73… D       
#&gt; 3 2018-10-16 00:00:00 DC    KDCA       RONALD REAGAN… AMERICA… B-73… D       
#&gt; 4 2018-10-12 00:00:00 DC    KDCA       RONALD REAGAN… AMERICA… B-73… D       
#&gt; 5 2018-09-04 00:00:00 DC    KDCA       RONALD REAGAN… AMERICA… A-319 D       
#&gt; 6 2018-09-01 00:00:00 DC    KDCA       RONALD REAGAN… AMERICA… A-321 D       
#&gt; # ℹ 1,222 more rows
#&gt; # ℹ 14 more variables: species_id &lt;chr&gt;, species &lt;chr&gt;, damage &lt;chr&gt;,
#&gt; #   num_engs &lt;dbl&gt;, incident_month &lt;dbl&gt;, incident_year &lt;dbl&gt;,
#&gt; #   time_of_day &lt;chr&gt;, time &lt;dbl&gt;, height &lt;dbl&gt;, speed &lt;dbl&gt;,
#&gt; #   phase_of_flt &lt;chr&gt;, sky &lt;chr&gt;, precip &lt;chr&gt;, cost_repairs_infl_adj &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Filter the rows for wildlife impacts that cost more than $1 million in damages:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(df, cost_repairs_infl_adj <span class="sc">&gt;</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 41 × 21
#&gt;   incident_date       state airport_id airport        operator atype type_eng
#&gt;   &lt;dttm&gt;              &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;          &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;   
#&gt; 1 2015-05-26 00:00:00 N/A   SVMI       SIMON BOLIVAR… AMERICA… B-73… D       
#&gt; 2 2015-04-25 00:00:00 FL    KJAX       JACKSONVILLE … AMERICA… A-319 D       
#&gt; 3 2015-04-02 00:00:00 MA    KBOS       GENERAL EDWAR… AMERICA… B-73… D       
#&gt; 4 2001-04-02 00:00:00 N/A   LFPG       CHARLES DE GA… AMERICA… B-76… D       
#&gt; 5 2015-10-08 00:00:00 WA    KSEA       SEATTLE-TACOM… DELTA A… A-330 D       
#&gt; 6 2015-09-23 00:00:00 UT    KSLC       SALT LAKE CIT… DELTA A… B-73… D       
#&gt; # ℹ 35 more rows
#&gt; # ℹ 14 more variables: species_id &lt;chr&gt;, species &lt;chr&gt;, damage &lt;chr&gt;,
#&gt; #   num_engs &lt;dbl&gt;, incident_month &lt;dbl&gt;, incident_year &lt;dbl&gt;,
#&gt; #   time_of_day &lt;chr&gt;, time &lt;dbl&gt;, height &lt;dbl&gt;, speed &lt;dbl&gt;,
#&gt; #   phase_of_flt &lt;chr&gt;, sky &lt;chr&gt;, precip &lt;chr&gt;, cost_repairs_infl_adj &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="sequence-operations-with-pipes" class="level3 page-columns page-full" data-number="12.2.4">
<h3 data-number="12.2.4" class="anchored" data-anchor-id="sequence-operations-with-pipes"><span class="header-section-number">12.2.4</span> Sequence operations with pipes (<code>%&gt;%</code>)</h3>
<div class="page-columns page-full"><p><img src="images/magrittr.png" class="img-fluid" width="200"> </p><div class="no-row-height column-margin column-container"><span class="margin-aside">Logo is a reference to <a href="https://en.wikipedia.org/wiki/The_Treachery_of_Images">The Treachery of Images</a> by Belgian surrealist painter René Magritte.</span></div></div>
<p>What if you want to select and filter at the same time? Well, one way to do this is to use intermediate steps. To do this, you first create a temporary data frame and then use that as input to the next function, like this:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>dc_impacts <span class="ot">&lt;-</span> <span class="fu">filter</span>(df, state <span class="sc">==</span> <span class="st">'DC'</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>dc_impacts_airlineTime <span class="ot">&lt;-</span> <span class="fu">select</span>(dc_impacts, operator, time, time_of_day)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dc_impacts_airlineTime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 6 × 3
#&gt;   operator           time time_of_day
#&gt;   &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt;      
#&gt; 1 AMERICAN AIRLINES  2130 Night      
#&gt; 2 AMERICAN AIRLINES  2043 Night      
#&gt; 3 AMERICAN AIRLINES   730 Dawn       
#&gt; 4 AMERICAN AIRLINES  2245 Night      
#&gt; 5 AMERICAN AIRLINES  2150 Night      
#&gt; 6 AMERICAN AIRLINES  2022 Night</code></pre>
</div>
</div>
<p>This works, but it can also clutter up your workspace with lots of objects with different names.</p>
<p>Another approach is to use <strong>pipes</strong>, which is a more recent addition to R. Pipes let you take the output of one function and send it directly to the next, which is useful when you need to do many things to the same dataset.</p>
<p>The pipe operator is <code>%&gt;%</code> and comes from the <a href="https://github.com/tidyverse/magrittr"><code>magrittr</code></a> package, which is installed automatically with <code>dplyr</code>. If you use RStudio, you can type the pipe with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>M</kbd> if you have a PC or <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>M</kbd> if you have a Mac. Here’s the same thing as the previous example but with pipes:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">'DC'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(operator, time, time_of_day) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 6 × 3
#&gt;   operator           time time_of_day
#&gt;   &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt;      
#&gt; 1 AMERICAN AIRLINES  2130 Night      
#&gt; 2 AMERICAN AIRLINES  2043 Night      
#&gt; 3 AMERICAN AIRLINES   730 Dawn       
#&gt; 4 AMERICAN AIRLINES  2245 Night      
#&gt; 5 AMERICAN AIRLINES  2150 Night      
#&gt; 6 AMERICAN AIRLINES  2022 Night</code></pre>
</div>
</div>
<p>In the above code, we use the pipe to send the <code>df</code> data frame first through <code>filter()</code> to keep only rows from DC, and then through <code>select()</code> to keep only the columns <code>operator</code>, <code>time</code>, and <code>time_of_day</code>.</p>
<p>Since <code>%&gt;%</code> takes the object on its left and passes it as the first argument to the function on its right, we don’t need to explicitly include the data frame as an argument to the <code>filter()</code> and <code>select()</code> functions.</p>
<p>Consider reading the <code>%&gt;%</code> operator as the words “…and then…”. For instance, in the above example I would read the code as “First, filter to only data from DC, <strong>and then</strong> select the columns <code>operator</code>, <code>time</code>, and <code>time_of_day</code>, <strong>and then</strong> show the first 6 rows.”</p>
<p>Here’s another analogy:</p>
<p><strong>Without Pipes</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leave_house</span>(<span class="fu">get_dressed</span>(<span class="fu">get_out_of_bed</span>(<span class="fu">wake_up</span>(me))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>With Pipes</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>me <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    wake_up <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    get_out_of_bed <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    get_dressed <span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    leave_house</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the above example, adding pipes makes the flow of operations easier to read from left to right, with the <code>%&gt;%</code> operator reading as “…and then…”</p>
<p>If you want to create a new object with the output of a “pipeline”, you just put the object name at the start of the first pipe:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>dc_impacts <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">'DC'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(operator, time, time_of_day)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dc_impacts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 6 × 3
#&gt;   operator           time time_of_day
#&gt;   &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt;      
#&gt; 1 AMERICAN AIRLINES  2130 Night      
#&gt; 2 AMERICAN AIRLINES  2043 Night      
#&gt; 3 AMERICAN AIRLINES   730 Dawn       
#&gt; 4 AMERICAN AIRLINES  2245 Night      
#&gt; 5 AMERICAN AIRLINES  2150 Night      
#&gt; 6 AMERICAN AIRLINES  2022 Night</code></pre>
</div>
</div>
</section>
<section id="sort-rows-with-arrange" class="level3" data-number="12.2.5">
<h3 data-number="12.2.5" class="anchored" data-anchor-id="sort-rows-with-arrange"><span class="header-section-number">12.2.5</span> Sort rows with <code>arrange()</code></h3>
<p>Use the <code>arrange()</code> function to sort a data frame by a column. For example, if you wanted to view the least expensive accidents, you could arrange the data frame by the variable <code>cost_repairs_infl_adj</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange by least expensive accident</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(cost_repairs_infl_adj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 56,978 × 21
#&gt;   incident_date       state airport_id airport        operator atype type_eng
#&gt;   &lt;dttm&gt;              &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;          &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;   
#&gt; 1 2013-09-05 00:00:00 MI    KFNT       BISHOP INTL A… SOUTHWE… B-73… D       
#&gt; 2 2011-04-17 00:00:00 TX    KDFW       DALLAS/FORT W… AMERICA… MD-80 D       
#&gt; 3 2018-07-10 00:00:00 NM    KABQ       ALBUQUERQUE I… SOUTHWE… B-73… D       
#&gt; 4 2017-10-31 00:00:00 PA    KPIT       PITTSBURGH IN… AMERICA… B-73… D       
#&gt; 5 2014-01-17 00:00:00 UT    KSLC       SALT LAKE CIT… SOUTHWE… B-73… D       
#&gt; 6 2006-04-28 00:00:00 TX    KIAH       GEORGE BUSH I… UNITED … B-73… D       
#&gt; # ℹ 56,972 more rows
#&gt; # ℹ 14 more variables: species_id &lt;chr&gt;, species &lt;chr&gt;, damage &lt;chr&gt;,
#&gt; #   num_engs &lt;dbl&gt;, incident_month &lt;dbl&gt;, incident_year &lt;dbl&gt;,
#&gt; #   time_of_day &lt;chr&gt;, time &lt;dbl&gt;, height &lt;dbl&gt;, speed &lt;dbl&gt;,
#&gt; #   phase_of_flt &lt;chr&gt;, sky &lt;chr&gt;, precip &lt;chr&gt;, cost_repairs_infl_adj &lt;dbl&gt;</code></pre>
</div>
</div>
<p>To sort in descending order, add the <code>desc()</code> function inside the <code>arrange()</code> function. For example, here are the <em>most</em> expensive accidents:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange by most expensive accident</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(cost_repairs_infl_adj))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 56,978 × 21
#&gt;   incident_date       state airport_id airport        operator atype type_eng
#&gt;   &lt;dttm&gt;              &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;          &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;   
#&gt; 1 2009-02-03 00:00:00 CO    KDEN       DENVER INTL A… UNITED … B-75… D       
#&gt; 2 2007-11-22 00:00:00 N/A   LFMN       NICE COTE D'A… DELTA A… B-76… D       
#&gt; 3 2011-09-26 00:00:00 CO    KDEN       DENVER INTL A… UNITED … B-75… D       
#&gt; 4 2017-07-11 00:00:00 CO    KDEN       DENVER INTL A… UNITED … B-73… D       
#&gt; 5 2008-10-25 00:00:00 UT    KSLC       SALT LAKE CIT… DELTA A… DC-9… D       
#&gt; 6 2011-07-30 00:00:00 CA    KBUR       BOB HOPE ARPT  SOUTHWE… B-73… D       
#&gt; # ℹ 56,972 more rows
#&gt; # ℹ 14 more variables: species_id &lt;chr&gt;, species &lt;chr&gt;, damage &lt;chr&gt;,
#&gt; #   num_engs &lt;dbl&gt;, incident_month &lt;dbl&gt;, incident_year &lt;dbl&gt;,
#&gt; #   time_of_day &lt;chr&gt;, time &lt;dbl&gt;, height &lt;dbl&gt;, speed &lt;dbl&gt;,
#&gt; #   phase_of_flt &lt;chr&gt;, sky &lt;chr&gt;, precip &lt;chr&gt;, cost_repairs_infl_adj &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="create-new-variables-with-mutate" class="level3" data-number="12.2.6">
<h3 data-number="12.2.6" class="anchored" data-anchor-id="create-new-variables-with-mutate"><span class="header-section-number">12.2.6</span> Create new variables with <code>mutate()</code></h3>
<p><img src="images/rstudio-cheatsheet-mutate.png" class="img-fluid" width="600"></p>
<p>You will often need to create new columns based on the values in existing columns. For this use <code>mutate()</code>. For example, let’s create a new variable converting the <code>height</code> variable from feet to miles:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">height_miles =</span> height <span class="sc">/</span> <span class="dv">5280</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(height, height_miles)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 56,978 × 2
#&gt;   height height_miles
#&gt;    &lt;dbl&gt;        &lt;dbl&gt;
#&gt; 1    700        0.133
#&gt; 2      0        0    
#&gt; 3     NA       NA    
#&gt; 4     NA       NA    
#&gt; 5     NA       NA    
#&gt; 6     NA       NA    
#&gt; # ℹ 56,972 more rows</code></pre>
</div>
</div>
<p>You can also create a second new column based on the first new column within the same call of <code>mutate()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">height_miles =</span> height <span class="sc">/</span> <span class="dv">5280</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">height_half_miles =</span> height_miles <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(height, height_miles, height_half_miles)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 56,978 × 3
#&gt;   height height_miles height_half_miles
#&gt;    &lt;dbl&gt;        &lt;dbl&gt;             &lt;dbl&gt;
#&gt; 1    700        0.133            0.0663
#&gt; 2      0        0                0     
#&gt; 3     NA       NA               NA     
#&gt; 4     NA       NA               NA     
#&gt; 5     NA       NA               NA     
#&gt; 6     NA       NA               NA     
#&gt; # ℹ 56,972 more rows</code></pre>
</div>
</div>
<p>You’ll notice that the variables created have a lot of <code>NA</code>s - that’s because there are missing data. If you wanted to remove those, you could insert a <code>filter()</code> in the pipe chain:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(height)) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">height_miles =</span> height <span class="sc">/</span> <span class="dv">5280</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(height, height_miles)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 38,940 × 2
#&gt;   height height_miles
#&gt;    &lt;dbl&gt;        &lt;dbl&gt;
#&gt; 1    700        0.133
#&gt; 2      0        0    
#&gt; 3    600        0.114
#&gt; 4      0        0    
#&gt; 5      0        0    
#&gt; 6      0        0    
#&gt; # ℹ 38,934 more rows</code></pre>
</div>
</div>
<p><code>is.na()</code> is a function that determines whether something is an <code>NA</code>. The <code>!</code> symbol negates the result, so we’re asking for every row where weight <em>is not</em> an <code>NA</code>.</p>
</section>
</section>
<section id="split-apply-combine" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="split-apply-combine"><span class="header-section-number">12.3</span> Split-apply-combine</h2>
<p>Many data analysis tasks can be approached using the <em>split-apply-combine</em> paradigm:</p>
<ol type="1">
<li>Split the data into groups</li>
<li>Apply some analysis to each group</li>
<li>Combine the results.</li>
</ol>
<p><code>dplyr</code> makes this very easy through the use of the <code>group_by()</code> function.</p>
<section id="the-group_by-function" class="level3" data-number="12.3.1">
<h3 data-number="12.3.1" class="anchored" data-anchor-id="the-group_by-function"><span class="header-section-number">12.3.1</span> The <code>group_by()</code> function</h3>
<p><img src="images/rstudio-cheatsheet-group_by.png" class="img-fluid" width="600"></p>
<p>The <code>group_by()</code> function enables you to perform operations across groups within the data frame. It is typically used by inserting it in the “pipeline” before the desired group operation. For example, if we wanted to add a a new column that computed the mean height of reported wildlife impacts for each state, we could insert <code>group_by(state)</code> in the pipeline:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(height)) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(state) <span class="sc">%&gt;%</span>          <span class="co"># Here we're grouping by state</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">mean_height =</span> <span class="fu">mean</span>(height)) <span class="sc">%&gt;%</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(state, mean_height)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 38,940 × 2
#&gt; # Groups:   state [59]
#&gt;   state mean_height
#&gt;   &lt;chr&gt;       &lt;dbl&gt;
#&gt; 1 FL           892.
#&gt; 2 IN           719.
#&gt; 3 FL           892.
#&gt; 4 FL           892.
#&gt; 5 TX          1177.
#&gt; 6 NY           937.
#&gt; # ℹ 38,934 more rows</code></pre>
</div>
</div>
<p>You’ll see that the same value for <code>mean_height</code> is reported for the same states (e.g.&nbsp;the mean height in Florida is 892 ft).</p>
</section>
<section id="the-summarize-function" class="level3" data-number="12.3.2">
<h3 data-number="12.3.2" class="anchored" data-anchor-id="the-summarize-function"><span class="header-section-number">12.3.2</span> The <code>summarize()</code> function</h3>
<p><img src="images/rstudio-cheatsheet-summarise.png" class="img-fluid" width="600"></p>
<p>The <code>group_by()</code> function is often used together with <code>summarize()</code>, which collapses each group into a single-row summary of that group. For example, we collapse the result of the previous example by using <code>summarise()</code> instead of <code>mutate()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(height)) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">mean_height =</span> <span class="fu">mean</span>(height))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 59 × 2
#&gt;   state mean_height
#&gt;   &lt;chr&gt;       &lt;dbl&gt;
#&gt; 1 AB           327.
#&gt; 2 AK           334.
#&gt; 3 AL           861.
#&gt; 4 AR           968.
#&gt; 5 AZ          2134.
#&gt; 6 BC           497.
#&gt; # ℹ 53 more rows</code></pre>
</div>
</div>
<p>You can also group by multiple columns - here let’s group by state and the airline:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(height)) <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(state, operator) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">mean_height =</span> <span class="fu">mean</span>(height))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; `summarise()` has grouped output by 'state'. You can override using the
#&gt; `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 213 × 3
#&gt; # Groups:   state [59]
#&gt;   state operator          mean_height
#&gt;   &lt;chr&gt; &lt;chr&gt;                   &lt;dbl&gt;
#&gt; 1 AB    AMERICAN AIRLINES        318.
#&gt; 2 AB    UNITED AIRLINES          350 
#&gt; 3 AK    AMERICAN AIRLINES          0 
#&gt; 4 AK    DELTA AIR LINES          414.
#&gt; 5 AK    UNITED AIRLINES          311.
#&gt; 6 AL    AMERICAN AIRLINES       1038.
#&gt; # ℹ 207 more rows</code></pre>
</div>
</div>
<p>Notice that in the above examples I’ve kept the early filter to drop <code>NA</code>s. This is important when performing summarizing functions like <code>mean()</code> or <code>sum()</code>. If <code>NA</code>s are present, the result will also be <code>NA</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">mean_height =</span> <span class="fu">mean</span>(height))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 59 × 2
#&gt;   state mean_height
#&gt;   &lt;chr&gt;       &lt;dbl&gt;
#&gt; 1 AB            NA 
#&gt; 2 AK           334.
#&gt; 3 AL            NA 
#&gt; 4 AR            NA 
#&gt; 5 AZ            NA 
#&gt; 6 BC            NA 
#&gt; # ℹ 53 more rows</code></pre>
</div>
</div>
<p>Once the data are grouped, you can also summarize multiple variables at the same time (and not necessarily on the same variable). For instance, you could add two more columns computing the minimum and maximum height:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(height)) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(state, operator) <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">mean_height =</span> <span class="fu">mean</span>(height),</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">min_height =</span> <span class="fu">min</span>(height),</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">max_height =</span> <span class="fu">max</span>(height))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; `summarise()` has grouped output by 'state'. You can override using the
#&gt; `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 213 × 5
#&gt; # Groups:   state [59]
#&gt;   state operator          mean_height min_height max_height
#&gt;   &lt;chr&gt; &lt;chr&gt;                   &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1 AB    AMERICAN AIRLINES        318.          0       1300
#&gt; 2 AB    UNITED AIRLINES          350           0       1400
#&gt; 3 AK    AMERICAN AIRLINES          0           0          0
#&gt; 4 AK    DELTA AIR LINES          414.          0       1700
#&gt; 5 AK    UNITED AIRLINES          311.          0       1200
#&gt; 6 AL    AMERICAN AIRLINES       1038.          0      11300
#&gt; # ℹ 207 more rows</code></pre>
</div>
</div>
</section>
<section id="counting" class="level3" data-number="12.3.3">
<h3 data-number="12.3.3" class="anchored" data-anchor-id="counting"><span class="header-section-number">12.3.3</span> Counting</h3>
<p>Often times you will want to know the number of observations found for each variable or combination of variables. One way to do this is to use the <code>group_by()</code> and <code>summarise()</code> functions in combination. For example, here is the number of observations for each aircraft engine type:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(type_eng) <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 5 × 2
#&gt;   type_eng count
#&gt;   &lt;chr&gt;    &lt;int&gt;
#&gt; 1 A            2
#&gt; 2 C           34
#&gt; 3 D        56705
#&gt; 4 F            3
#&gt; 5 &lt;NA&gt;       234</code></pre>
</div>
</div>
<p>Since this is such a common task, <code>dplyr</code> provides the <code>count()</code> function to do the same thing:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(type_eng)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 5 × 2
#&gt;   type_eng     n
#&gt;   &lt;chr&gt;    &lt;int&gt;
#&gt; 1 A            2
#&gt; 2 C           34
#&gt; 3 D        56705
#&gt; 4 F            3
#&gt; 5 &lt;NA&gt;       234</code></pre>
</div>
</div>
<p>For convenience, <code>count()</code> also provides the <code>sort</code> argument:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(type_eng, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 5 × 2
#&gt;   type_eng     n
#&gt;   &lt;chr&gt;    &lt;int&gt;
#&gt; 1 D        56705
#&gt; 2 &lt;NA&gt;       234
#&gt; 3 C           34
#&gt; 4 F            3
#&gt; 5 A            2</code></pre>
</div>
</div>
<p>You can also count the <em>combination of variables</em> by providing more than one column name to <code>count()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">count</span>(type_eng, num_engs, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 10 × 3
#&gt;   type_eng num_engs     n
#&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;
#&gt; 1 D               2 53652
#&gt; 2 D               3  2753
#&gt; 3 D               4   299
#&gt; 4 &lt;NA&gt;           NA   232
#&gt; 5 C               2    34
#&gt; 6 F               2     3
#&gt; # ℹ 4 more rows</code></pre>
</div>
</div>
<p>Hmm, looks like most reported wildlife impacts involve planes with 2 D-type engines.</p>
</section>
</section>
<section id="exporting-data" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="exporting-data"><span class="header-section-number">12.4</span> Exporting data</h2>
<p>Now that you have learned how to use <code>dplyr</code> to extract information from or summarize your raw data, you may want to export these new data sets. Similar to the <code>read_csv()</code> function used for reading CSV files into R, there is a <code>write_csv()</code> function that generates CSV files from data frames.</p>
<p><strong>Important</strong>: Before using <code>write_csv()</code>, create a new folder called “data_output” and put it in your R Project folder. In general, you should never write generated datasets in the same directory as your raw data. The “data” folder should only contain the raw, unaltered data, and should be left alone to make sure we don’t delete or modify it.</p>
<p>Let’s save one of the summary data frames from the earlier examples where we computed the min, mean, and max heights of impacts by each state and airline:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>heightSummary <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(height)) <span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(state, operator) <span class="sc">%&gt;%</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">mean_height =</span> <span class="fu">mean</span>(height),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">min_height =</span> <span class="fu">min</span>(height),</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">max_height =</span> <span class="fu">max</span>(height))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; `summarise()` has grouped output by 'state'. You can override using the
#&gt; `.groups` argument.</code></pre>
</div>
</div>
<p>Save the the new <code>heightSummary</code> data frame as a CSV file in your “data_output” folder:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(heightSummary, <span class="at">path =</span> <span class="fu">file.path</span>(<span class="st">'data_output'</span>, <span class="st">'heightSummary.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="tips" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="tips"><span class="header-section-number">12.5</span> Tips</h2>
<p>You will often need to create new variables based on a condition. To do this, you can use the <code>if_else()</code> function. Here’s the general syntax:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">if_else</span>(<span class="sc">&lt;</span>condition<span class="sc">&gt;</span>, <span class="sc">&lt;</span><span class="cf">if</span> <span class="cn">TRUE</span><span class="sc">&gt;</span>, <span class="sc">&lt;</span><span class="cf">else</span><span class="sc">&gt;</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The first argument is a condition. If the condition is TRUE, then the value given to the second argument will be used; if not, then the third argument value will be used.</p>
<p>Here’s an example of creating a variable to determine which months in the wildlife impacts data are in the summer:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">summer_month =</span> <span class="fu">if_else</span>(incident_month <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>), <span class="cn">TRUE</span>, <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Of course, in this particular case the <code>if_else()</code> function isn’t even needed because the condition returns <code>TRUE</code> and <code>FALSE</code> values. However, if you wanted to extend this example to determine all four seasons, you could use a series of nested <code>if_else()</code> functions:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">season =</span> <span class="fu">if_else</span>(</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>        incident_month <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>), <span class="st">'Spring'</span>, <span class="fu">if_else</span>(</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>        incident_month <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>), <span class="st">'Summer'</span>, <span class="fu">if_else</span>(</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>        incident_month <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>), <span class="st">'Fall'</span>, <span class="st">'Winter'</span>)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>    )))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note: The Base R version of this function is <code>ifelse()</code>, but I recommend using the <code>dplyr</code> version, <code>if_else()</code>, as it is a <a href="https://stackoverflow.com/questions/50646133/dplyr-if-else-vs-base-r-ifelse">stricter function</a>.</p>
</section>
<section id="page-sources" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="page-sources">Page sources</h2>
<p>Some content on this page has been modified from other courses, including:</p>
<ul>
<li><a href="https://datacarpentry.org/R-ecology-lesson/">Data Analysis and Visualization in R for Ecologists</a>, by François Michonneau &amp; Auriel Fournier. Zenodo: http://doi.org/10.5281/zenodo.3264888</li>
<li>The amazing illustrations by <a href="https://github.com/allisonhorst">Allison Horst</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/p4a\.jhelvy\.com\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./data-frames.html" class="pagination-link" aria-label="Data Frames">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data Frames</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./data-visualization.html" class="pagination-link" aria-label="Data Visualization">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Data Visualization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Programming for Analytics in R was written by John Paul Helveston</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/jhelvy/p4a/edit/main/data-wrangling.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/jhelvy/p4a/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>